### ISSUE TITLE
[Feature Request]: Create Products by Rental Business Employees

### ISSUE THREAD

**Issue by alexkagzz** [alexkagzz/jmix-rys#17]
### feature description

As a Rental Business Employee
I want to create rental construction products (like mini excavators) with their general attributes
So that I can register stock items of this product for later rentals

**Comment by alexkagzz** [comment]
### TODOs

- [x] create product entity
- [x] store product information, like name, description, images
- [x] allow configuring flat pricing like 50 EUR/day, 80 Eur per week

**Comment by alexkagzz** [comment]
Resolved by commit #18
