### ISSUE TITLE
[Feature Request]: Organise Products in product Categories by Rental business Employees

### ISSUE THREAD

**Issue by alexkagzz** [alexkagzz/jmix-rys#23]
### feature description

As a Rental Business Employee
I want to manage product categories and group products in categories
So that customers have a better overview of the different kinds of products I offer.

**Comment by alexkagzz** [comment]
### TODOs
---

- [x] create ProductCategory entity
- [x] managed product categories through the UI
- [x] create optional association between products and product categories

**Comment by alexkagzz** [comment]
Resolved by commit #24
