### ISSUE TITLE
[Feature Request]: Support multiple rental businesses on the platform by Rent-Your-Stuff Ltd.

### ISSUE THREAD

**Issue by alexkagzz** [alexkagzz/jmix-rys#27]
### feature description

As Rent-Your-Stuff Inc.
We want to offer Rent-Your_stuff to multiple Rental businesses
So that we can offer Rent-Your_stuff at a lower price per customer.

**Comment by alexkagzz** [comment]
### TODOs
---

- [x] Enable multi-tenancy within the application
- [x] make User entity & management UI tenant aware
- [x] Make business entities' tenant aware
- [x] Change the Login screen to support multitenancy

**Comment by alexkagzz** [comment]
Resolved via commit #28
